#ifndef PACKET_H
#define PACKET_H

#define PACKET_FLAG 0x7E
#define MAX_ENCODED_BYTES 512
#ifndef ARDUINO
#define MAX_DECODED_BYTES (254 * (MAX_ENCODED_BYTES - 1) / 255)
#else
#define MAX_DECODED_BYTES 508
#endif
#define MAX_PACKET_SIZE (MAX_ENCODED_BYTES + 6)

#endif // PACKET_H
